App\Entity\Product:
  properties:
    name:
      - NotNull:
      - Type: string
    price:
      - NotNull: ~
      - Type: integer
    picture:
      - NotNull: ~
<<<<<<< HEAD
      - Type: string
=======
      - Type: string
>>>>>>> f62e8f4788244a6d81ec57b1ab3c863dcc4a3347
